### ISSUE TITLE
Refactor `createLiquidation` inequality

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#1003]
Right now the `createLiquidation` function has the following require:
```
require(amountToLiquidate.isGreaterThanOrEqual(positionCollateral.sub(positionToLiquidate.withdrawalRequestAmount)));
```

This should be refactored to be a strict equality to correctly prevent liquidation front running from either a position holder's `deposit` or `withdrawl`s of collateral while a liquidation pends in the mempool.

**Comment by ptare** [comment]
I think this was a deliberate choice?

If the check were a strict equality, the sponsor could deposit 1 Wei and stop the liquidation from going through. Whereas with a greaterThan, the liquidator could, in theory, specify the max collateral they are willing to liquidate up to.

Happy to discuss offline. I could also be totally wrong on all this.
