### ISSUE TITLE
Implement partial liquidations

### ISSUE THREAD

**Issue by ptare** [UMAprotocol/protocol#1006]
A proposal for how they should behave:

```
        // Position has C collateral. Pending withdrawal of W collateral. T tokens outstanding.
        // Liquidator wants to liquidate L tokens, with up to P collateral per token.
        // Position is treated like it has (C - W) collateral.
        // Liquidation is allowed if P >= (C - W) / T, to address any front running.
        // Burn L tokens and set T = T - L.
        // We've blown away L / T of the Position.
        // C = (1 - L/T) * C
        // W = (1 - L/T) * W
        // Liquidation has L/T * C rawLockedCollateral and L/T * W of liquidatedCollateral.
```

@mrice32 @chrismaree @nicholaspai Thoughts on this approach?

**Comment by mrice32** [comment]
Seems reasonable to me.

**Comment by ptare** [comment]
Mostly wanted to make sure I was handling pending withdrawals correctly.

**Comment by nicholaspai** [comment]
agreed. Just be conscious of rounding errors since I see lots of divisions. By default, amount to partially liquidate could get rounded down, and remaining sponsor position would get rounded up. That's not a bad thing.

**Comment by ptare** [comment]
Some of the fee changes have complicated this logic. @mrice32 Can we discuss offline to figure out how partial liquidations should work and handle fees correctly?
