### ISSUE TITLE
Limit the token decimals in the NFCT to 18 points

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#1008]
Right now any ERC20 token can be listed as a reserve currency with no logical checks performed on them. However, all mathematics assumes that there are 18 decimal points within a token. This means that a collateral currency with anything other than 18 decimal points will cause issues. A check should be implemented to ensure that only 18 decimal point tokens can be added as collateral currency.

**Comment by nicholaspai** [comment]
We address this by (1) forcing all synthetic tokens to be created via `ExpiringMultiPartyCreator` and (2) whitelisting collateral token addresses

#1022
