### ISSUE TITLE
Expose fee calculation data so that clients (i.e. CLI tool) can calculate collateral net of fees

### ISSUE THREAD

**Issue by nicholaspai** [UMAprotocol/protocol#1020]
Two possible ways for someone to know their collateral net of fees:
- Emit events for all fee collections
- Make `cumulativeFeeMultiplier` public and emit this value at important points such as in the `PositionCreated` event

**Comment by nicholaspai** [comment]
This might already be handled by `getCollateral` and the usage of `rawCollateral` in the `PositionData` struct

**Comment by nicholaspai** [comment]
@ptare has this been an issue for you?

**Comment by mrice32** [comment]
Note: the fee multiplier is already public: https://github.com/UMAprotocol/protocol/blob/b8af725f1e51fc3878bb52c73bd0f541e01ef30e/core/contracts/financial-templates/implementation/FeePayer.sol#L44

**Comment by nicholaspai** [comment]
Test case I'd be curious about whether you can correctly calculate collateral net of fees:
- (T=0) Store sets fee `F`, where `1 > F > 0`
- (T=0) Sponsor 1 creates a position with collateral `C_1`
- (T=1) Sponsor 1 can read their position inclusive of fees via `getCollateral()`, which should be `(C_1 * (1-F))`
- (T=1) Sponsor 2 creates a position with collateral `C_2`
- (T=2) Sponsor 2 can read their position inclusive of fees, which should be `(C_2 / (1-F)) * (1-F)^2`

Any other edge cases I'm missing?
