### ISSUE TITLE
Refactor `testable.sol` to report one constant time from all contracts that use it

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#1047]
Right now different deployed contracts can have different notions of the time. This can cause reverts in inter-contract calls which have different interantil returns from `getCurrentTime()` from their instance of `testable.sol`.

This should be thought about and fixed.

Consider storing a canonical time in some other location (eg finder).

**Comment by nicholaspai** [comment]
Finder probably makes sense, each contract could look up the finder's time and we could have Finder inherit Testable

**Comment by chrismaree** [comment]
yup. I agree. Problem is seperation of conserns gets a bit muddled with this.

**Comment by chrismaree** [comment]
We could have a seperate canonical time location that all time contracts inheret from. This is registered in the finder.
