### ISSUE TITLE
Handle withdraw requests that are larger than the user's collateral

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#1049]

**Comment by nicholaspai** [comment]
Assuming this should be handled in `withdrawPassedRequest()` and `withdraw()`, and I'm guessing you're trying to request that explicitly check that the amount to withdraw (whose `rawValue` is passed into `safeTransfer(sponsor)` is <= the user's collateral.

**Comment by nicholaspai** [comment]
While working through this, we've produced a couple realizations:
1) `withdraw()` will never allow the user to withdraw their full balance because the GCR check will fail
2) If a pending withdrawAmount > collateralAmount, then the position should get liquidated immediately. 

Is this a moot issue?
