### ISSUE TITLE
Add method to `ExpiringMultiPartyClient` to return the `id` and `sponsor` that can be withdrawn by a liquidator, disruptor or sponsor

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#1050]
Right now there is no way to know about which positions can be withdrawn after a liquidation.

**Comment by nicholaspai** [comment]
@ptare do you think this would be a worthy feature for the CLI?

**Comment by nicholaspai** [comment]
`withdrawLiquidation` reverts if not withdrawable. We decided not to add an contract method returning all withdrawable liquidations
