### ISSUE TITLE
Anchors in markdown and images do not reflect in site

### ISSUE THREAD

**Issue by rcai1** [UMAprotocol/protocol#1055]
In the "Creating Synthetic Tokens from Truffle Console" tutorial, we link to different parts of the page depending on whether or not the tokens you are creating come from a pre-deployed contract or not. While the markdown renders correctly in the Github preview, it does not reflect in the site.

**Comment by hlambur** [comment]
Here's a more explicit example I showed @mrice32 (and he asked me to write here).

In markdown this link works:
`tutorials/creating_synthetic_tokens_from_truffle_console.md#create-new-tokens-from-an-existing-contract`

But we need it parsed to this for docs.umaproject:
tutorials/creating_synthetic_tokens_from_truffle_console.html#_create_new_tokens_from_an_existing_contract

**Comment by hlambur** [comment]
also I have attempted to add images that are centered and resized using this code:
```
<p align="center">
34
  <img src="st_create_contract.png" width="500">
35
</p>
```
Found here for example: https://github.com/UMAprotocol/protocol/blame/rcai1-patch-1/documentation/explainers/synthetic_tokens.md#L33-L35

This code does not parse into our docs.umaproject site—the images don't show up at all.
