### ISSUE TITLE
Change disputeId and liquidationId to just id in EMP events

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#1058]
IIUC, this value is the same id, but it's called different things in different events. I think it would be less confusing if we referred to it as `id` as we do elsewhere in the contract. Another option would be to call it `liquidationId`. Thoughts @chrismaree?

**Comment by mrice32** [comment]
Example: https://github.com/UMAprotocol/protocol/blob/b8af725f1e51fc3878bb52c73bd0f541e01ef30e/core/contracts/financial-templates/implementation/Liquidatable.sol#L96

**Comment by chrismaree** [comment]
I think this is a good idea. We also use the notion of a `uuid` in some places and an `id` in others. this should all be made to be consistent.
