### ISSUE TITLE
Increase scope of variables emitted from EMP

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#1059]
Right now the events emitted are not expressive enough for some basic debugging of faulty transactions or strange stage changes. Specifically, as a result of `withdrawLiquidation` deleting the liquidation object with `delete liquidations[sponsor][id]`, some information can be lost (or become hard to put together after the fact). If more information was emitted this would make this debugging easier. 

For example:
the `_settle` function should emit the `settlementPrice`.
etc.

More will be added to this list as we go along.

**Comment by nicholaspai** [comment]
@chrismaree @mrice32 @ptare do we still think its worth emitting the settlement price (or alternatively, the price request timestamp) with `settleExpired`?

Any other events we should be emitting?
