### ISSUE TITLE
Dynamic gas costs for liquidator and dispute bots

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#1062]
Right now the bots hard code how much they spend on gas. this should change to getting the value from something like the https://ethgasstation.info/

**Comment by nicholaspai** [comment]
Agreed, here's an example of dynamically fetching it: https://github.com/dydxprotocol/liquidator/blob/master/src/lib/gas-price.js

**Comment by chrismaree** [comment]
Using the https://docs.ethgasstation.info/ seems reasonable as well.
