### ISSUE TITLE
Notion of "Expiration Time" is not consistent between functions

### ISSUE THREAD

**Issue by nicholaspai** [UMAprotocol/protocol#1145]
The position and liquidation liveness (i.e. when a position "expires" and `expire()` can be called, and when `withdrawLiquidation()` can be called after a liquidation expires) *expires exactly at the expiry time*:

```Expiry >= start_timestamp + liveness ```

However, the withdrawal liveness (i.e. when `withdrawPassedRequest()` can be called) *expires after the expiry time*:

```Expiry > start_timestamp + liveness``` 

To improve user experience, we should make the notion of "expiry" consistent, and I am in favor of changing withdrawal expiry to the way that position and liquidation expiry are defined: the liveness expires upon, not after, the completion of the liveness.

**Comment by mrice32** [comment]
+1
