### ISSUE TITLE
Sponsor CLI improvements based on user feedback

### ISSUE THREAD

**Issue by ptare** [UMAprotocol/protocol#1156]
Potential improvements to consider:
1. Provide collateral currency when listing markets
2. Change "borrow" to "mint" in language
3. Expand messaging around withdraw request vs. instantaneous withdrawals
4. Show synthetic token balances in the Wallet section
5. No way to abort prompts, e.g., "How much to withdraw?". You have either Ctrl+C the script or enter an amount and then select "No" on confirmation.
6. On multiple transactions, explain how many there are, e.g., "1/3".
7. Consider explaining the GCR mechanic somewhere
8. Consider reprinting details about the sponsor's position after taking action (so they can see what has changed as a result of their create/redee/whatever)
9. Show min sponsor token size?

A bigger chunk of work:
1. Build the full flow around expiration, including a token holder flow.
2. Add flags in addition to the interactive mode

**Comment by chrismaree** [comment]
@nicholaspai what from this list would you say is still outstanding and needs work?

**Comment by nicholaspai** [comment]
I'm going to close this as all issues were addressed, new CLI feature requests can be turned into new issues
