### ISSUE TITLE
Inefficient use of the empClient's update function in liquidator and dispute bots

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#1176]
Right now the liquidator bot calls `this.empClient._update()` on both the `queryAndLiquidate` call and `queryAndWithdrawRewards` call from the `index.js`. This means the client is updated two times per polling period from `index.js`. This doubles the number of calls.

Either this update should be called from `index.js` or the emp client should use a similar rate limiting system to the `GasEstimator.js` that ensures that enough time has passed between calls.

**Comment by nicholaspai** [comment]
What do you think about doing both caching and calling `_update` from `index.js`?

I think both the liquidator/disputer bots should call `_update` from their `index.js` root script. However,  I also like using the caching system as in `GasEstimator`, which would require EMPClient storing at least two variables, `lastUpdateTime` and `updateThreshold`.

This caching would come in handy if one account is running both the liquidator and disputer bots at the same time. So, if this account successively calls `queryAndLiquidate`, `queryAndWithdraw`, `queryAndDispute`, and finally `queryAndWithdraw`, but there are no new potential liquidations or disputes, then only one `_update` is needed to be called

 We could also add a `forceUpdate` method that a liquidator or disputer bot can call after they execute a state-changing action like `createLiquidation` or `dispute` or `withdraw`.
