### ISSUE TITLE
Consider documenting mainnet and testnet addresses

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#1224]
Something like [this](https://opyn.gitbook.io/opyn/abis-smart-contract-addresses) on our docs site might make sense.

cc @rcai1 @hlambur

**Comment by EdsonAlcala** [comment]
I actually was going to ask about this

**Comment by rcai1** [comment]
This is handled in this PR: https://github.com/UMAprotocol/protocol/pull/1279
