### ISSUE TITLE
Reconsider gas limits on read calls

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#136]
Some of our smart contracts have `view` functions that return unbounded arrays (all meant for offchain inspection and not to be used by other contracts onchain). We would like to understand what the bounds are before the functions stop working due to gas limits within read calls to geth or parity. Ultimately, we may deem it necessary to implement some sort of pagination for these functions, but as of now, we are assuming that these arrays will not get too large.

See [here](https://github.com/paritytech/parity-ethereum/issues/6293) for a someone discussing a similar issue.

**Comment by DeRain** [comment]
HI @mrice32. Have you reached or calculated limits for this?

**Comment by mrice32** [comment]
Nope, we’ve never run into any issues here because we’ve never attempted to return arrays that have more than 10s or 100s of elements in practice. @DeRain are you familiar with where these limits are for different client implementations?

**Comment by DeRain** [comment]
@mrice32 Unfortunately not familiar. 

In practice, we returned up to 300 `uint256` values from function and all was fine. I think this is a great topic for investigation and maybe for a publication :)
