### ISSUE TITLE
More consistently use `this.web3.utils.toWei`

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#1411]
right now we are quite inconsistent with importing `toWei`. Sometimes we import it from `web3.utils` at the top of a script and some times we call it on the web3 object. this should be more consistent throughout the code base.

**Comment by nicholaspai** [comment]
Totally agreed. I think we should always import it from `web3.utils` at the top of any method or script/class that uses `toWei/toBN/fromWei` more than once. `web3.utils.X` is a handful to type out.
