### ISSUE TITLE
Refactor bot CI pipeline to pull configs from GCP rather than env params

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#1502]
All our configurations are stored on GCP. The bots should pull down their own configs at initialization rather than having them passed to them. As a starting point this command will get the name of the instance:
```
sed 's/.\{50\}$//' <<< $(curl http://metadata.google.internal/computeMetadata/v1/instance/hostname -H Metadata-Flavor:Google)
```

**Comment by mrice32** [comment]
A hackier way that would allow us to achieve the same thing would be to have the deployment scripts pull the config from gcloud into a temp directory just before deployment and use the instance name to determine the config to use. Thoughts?

**Comment by chrismaree** [comment]
> A hackier way that would allow us to achieve the same thing would be to have the deployment scripts pull the config from gcloud into a temp directory just before deployment and use the instance name to determine the config to use. Thoughts?

This is also a good option. The one difference with this is that we'll no longer be able to use the cloud `create-with-container` function as GCP will no longer be running the containers. Rather, this implementation would need this startup script to execute a `docker run` command followed by the configs that were just pulled down. 

some downsides to both my proposed solution and your hackier one are:
1) we can no longer see the env variables set in the GCP dashboard.
2) we no longer use the GCP deployment flow for containers that are optimized for their platform.
