### ISSUE TITLE
[Ongoing] New features for next version of EMP

### ISSUE THREAD

**Issue by nicholaspai** [UMAprotocol/protocol#1553]
Event changes:
- [ ] **Better new sponsor events**: `NewSponsor` event should emit token and collateral amounts that new sponsor seeded position with. Makes accounting for new sponsor positions easier.
- [x] **LiquidationCreated event**: should include `liquidationTime` to make testing easier. Currently we assume that the liquidation was created at the `block.timestamp` of the mined event, but this is not the case when testing with the `Testable` contract.
- [x] **LiquidationWithdrawn event**: should include `settlementPrice`, `liquidationId` and `sponsor`. `settlementPrice` is only retrievably currently by making a `oracle.getPrice()` call, so accounting would be easier if we included this in the event. Also, as long as none of the liquidation-related events include a `liquidationTime`, there is no deterministic way to retrieve the liquidationTime and make the `getPrice()` call accurately. This isn't a problem on public networks where the `liquidationTime == block.timestamp` but this is an issue for testing locally.

Non-event changes:
- [ ] **Block 0 token liquidations**: `createLiquidation()` should disallow `maxTokensToLiquidate == 0`

**Comment by daywiss** [comment]
there are 2 kind of limitations here. one is the stack depth within the functions, and the other is the contract size approaching max limit. 
The stack limit is being hit in both liquidationCreated and liqudidationWithdrawn events. 
liquidationCreated only allows 1 additional event value, ive included `liquidationTime`
liquidationWithdrawn allows 1 additional  event, i've included `settlementPrice`
This leaves 15 bytes within limit.
