### ISSUE TITLE
Issue regarding gRPC binary when running Truffle Compile on Ubuntu

### ISSUE THREAD

**Issue by adrianmcli** [UMAprotocol/protocol#1623]
The following occurred during a run-through of the Liquidator Bot tutorial with an Ubuntu user. 

After running `npm install` at project root, the user navigated inside the `core` directory and ran `npx truffle compile` and received this error:

```
Error: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"
Original error: Cannot find module '/home/evan/nodejs/protocol/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc/grpc_node.node'
    at Object.<anonymous> (/home/evan/nodejs/protocol/node_modules/grpc/src/grpc_extension.js:43:17)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load 
```

On my local machine, I [ran](https://docs.npmjs.com/cli/ls.html) `npm ls` to find out where the `grpc` module was used and this is what was printed out.

```
protocol@0.1.0 /Users/adrianli/dev/protocol
└─┬ @google-cloud/kms@0.3.0
  └─┬ google-gax@0.23.0
    └── grpc@1.24.2
```

Subsequently, after the user ran `npm rebuild`, another error occurred when running `npx truffle compile`:

```
Cannot find module @umaprotocol/truffle-ledger-provider
```

When the user ran `npm ls @umaprotocol/truffle-ledger-provider`, they got an `UNMET PEER DEPENDENCY error` instead of what is expected:

```
protocol@0.1.0 /Users/adrianli/dev/protocol
└── @umaprotocol/truffle-ledger-provider@1.0.3
```

**Comment by adrianmcli** [comment]
My guess is that `npm rebuild` messed something up and somehow unlinked the provider package from his `node_modules`. I would be curious to see if we can replicate this issue on someone else's Ubuntu machine.

**Comment by mrice32** [comment]
@adrianmcli Can we close this since it's the same as #1625? Or do you want to verify that the fix proposed there solves this issue before closing?

**Comment by adrianmcli** [comment]
Yeah we can close this in favour of #1625
