### ISSUE TITLE
Voter Dapp: simplify admin proposal voting

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#1649]
The voter dapp should show a "yes" or "no" choice rather than making the user type 1 or 0.

**Comment by adrianmcli** [comment]
I know we talked about a dropdown, but I'm partial to radio buttons: https://material-ui.com/components/radio-buttons/#radio

**Comment by nicholaspai** [comment]
Can follow [this pattern](https://github.com/UMAprotocol/protocol/blob/62fd046f4523d66f1abab527878e59f09c1194ad/voter-dapp/src/ActiveRequests.js#L554) to decide if request is an admin proposal.
