### ISSUE TITLE
Limit voter dapp price entry field to only take numbers

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#1665]

**Comment by nicholaspai** [comment]
The `TextField` component should specify `type=number"`

**Comment by adrianmcli** [comment]
Just trying to understand the dapp code a little bit, but this is the component that needs the additional attribute right?

https://github.com/UMAprotocol/protocol/blob/effa709ebc721d95c69c83c3338c91c2f992c2f1/voter-dapp/src/ActiveRequests.js#L411-L414

**Comment by nicholaspai** [comment]
Yep that's the one
