### ISSUE TITLE
[Ongoing] New features for next version of DVM

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#1697]
- [ ] **Batch rewards retrieval**: Right now each round of rewards retrieved needs to be a separate tx. For example, if I commit, reveal on rounds 1 and 2 I need to send 2 transactions to retrieve these rewards. Having a batch retrieve rewards function would make this execute in 1tx.

**Comment by nicholaspai** [comment]
Deprecating in favor of #1604
