### ISSUE TITLE
Create liquidator and disputer price overrides

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#1702]
Right now there is no way to force the liquidator & disputer bots to execute at a given price point. There should be the ability to override the price that the liquidator and dispute bots execute at with a provided env variable.

**Comment by chrismaree** [comment]
There are however some pretty serious consequences with misconfiguring this env parameter such as a bot executing an invalid liquidation and potentially losing the bot operator money. 

Also, how does this kind of override interact with the disputer, given the disputer is operating retroactively (disputing historic liquidations within the licenses period)?

**Comment by nicholaspai** [comment]
> There are however some pretty serious consequences with misconfiguring this env parameter such as a bot executing an invalid liquidation and potentially losing the bot operator money.

I think we should handle this worst-case scenario by sanity-cheking the overriden value and defaulting to the pricefeed's value.

By the way, is this issue going to be resolved by #1706 ?

**Comment by chrismaree** [comment]
yup. that PR should close this issue.

We can add some sanity-checking to it but what would be a reasonable way to do this? checking the input type or range? problem with the range is we have some pretty wide prices that the DVM can resolve.
