### ISSUE TITLE
Add retry logic to price feeds

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#1714]
The current price feed implementation is pretty fragile: if the price feed returns a malformed response or something goes wrong in the query the bot falls over. They handle this error pretty gracefully by not crashing the process but there is no retry logic. 

Ideally, the price feeds should try two or three times before throwing an error.

**Comment by nicholaspai** [comment]
So from my experience I've seen API outages that last for > 30 mins, as opposed to individual failed requests. Retry-ing wouldn't help as much here

**Comment by chrismaree** [comment]
Ye, I 've seen the same. perhaps having a redundant feed is the best bet?
