### ISSUE TITLE
Should be able to run `$(npm bin)/truffle x` from every lerna package, not just from `core`

### ISSUE THREAD

**Issue by nicholaspai** [UMAprotocol/protocol#1731]
To run truffle, a package must list truffle as a dependency, have a truffle-config.js file, and have access to any contracts

**Comment by adrianmcli** [comment]
lol I was going to joke that this is a bug not a feature and that you should _not_ be trying to run truffle in literally every package. But I understand that it's a necessary migration step.

**Comment by mrice32** [comment]
Fixed by https://github.com/UMAprotocol/protocol/pull/1776.
