### ISSUE TITLE
Make liquidator bots more capital efficient

### ISSUE THREAD

**Issue by kendricktan** [UMAprotocol/protocol#1741]
> The liquidator bot must currently hold the synthetic tokens it uses for EMP liquidations. To make these bots more capital efficient (and flexible), they should be able to hold a generic stablecoin and convert that stablecoin to the synthetic token when needed for a liquidation. It might make the most sense to use an aggregator, like 1inch to do the trade

For reference, 1inch address is @ 0x11111254369792b2Ca5d084aB5eEA397cA8fa48B, documentation is at https://github.com/CryptoManiacsZone/1inchProtocol

Question: Also can't we just use flashloans for this? Or is there a liveliness period?

### Additions:
- A function that will swap <x> amount of token <a> with <y> amount of token <b>

### Execution Flow:
1. Bot checks if sponsor is fully collateralized
2.1. If they are, go back to step 1
2.2. If they aren't, and we don't have enough of the synthetic tokens, we swap our stablecoins to the synthetic token
3. Once we get the rewards we convert the syntheic tokens back to stablecoins, should the market be liquid enough

**Comment by mrice32** [comment]
There’s a liveness period, so flash loans won’t work, sadly.
