### ISSUE TITLE
[Ongoing] New features for next version of bot infrastructure

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#1762]
The liquidator, disrupter, and monitor bots are the backbone of the UMA infrastructure. There is a long list of improvements and possible refactors that can make them more stable, easier to reason about, simpler, and all-round better. 

This issue intends to be a "wishlist" for bot related features and changes. It will be an initial place to list and discuss issues of relevance after which refinement specific issues should be created and referenced back to this issue.

1) **Git ops for bot configs.** Bot configs should reside within a CI & version-controlled Github repo. This enables both manual and automated verification of configurations as well as a more robust ability to roll back if need be.
2) **Typescript implementation.** Key parts of the bots can (and should) rely on more strictly typed languages. This issue could materialize by refactoring key parts of the bots to use typescript such as implementing all clients & pricefeeds in typescript.
3) **Decouple from truffle.** The bots should be able to run as a node process on their own. Currently, all bots require execution using a `truffle exec ...` command which injects `web3.js` and contract artifacts. Ideally, this should be changed to remove the dependency on Truffle. Implementation of this should see the bots importing contract ABIs and using a web3 dependency to remove all links to Truffle.
4) **Simple bot docs for "getting started"**. There should be an addition to the current docs that offers a single line execution from a package & docker container. This should ideally use the "UMA.js" package that has all the constructed contract ABIS. and offers a dead-simple execution.
5) **Minimum viable bot.** The current bot infrastructure is pretty daunting for users that want to build on it. Creating a simple "toy" example would be very useful for builders and bot operators alike. This could either live in a separate repo or within the current protocol repo. See the "demo" [Deposit Box contract](https://github.com/UMAprotocol/protocol/tree/master/core/contracts/financial-templates/demo) for an example of a MVP build on more complex UMA infrastructure.
6) **Pull common logic into a common library**. There is a lot of common UMA logic such as pricefeeds, ABIS, contract deployment addresses. Ideally, these should all be accessible from one UMA.js library. This issue will properly need to be solved to achieve issues above 3 & 5.
7) **Improving how configs are stored**. Right now we use json objects. can we improve this? how can we build CI around these configs to make things more robust?
9) **Generalize bots to the point that they can be run in a front end.** This issue is more open-ended. What would be ideal is if the UMA.js library was generalized enough to the point that it could be imported into a front end such that we could offer a "click and liquidate" functionality that leveraged the same logic as the liquidator bots themselves.
10) **Improve error handeling**. Crypto watch price feed throws errors and we dont deal with this well. There should be more robust logging around these kinds of errors.
11) **Re-try logic.** The bots are very fragile with errors that occur and often fail without re-trying. A simple refinement here would be some notion of re-try logic. If it fails, the bots should re-try a second time before throwing an error.

**Comment by daywiss** [comment]
We should circle back to this at some point, lots of good stuff here. I think actually point 10 is my number one feature right now.
