### ISSUE TITLE
Voterdapp stat issue

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#1769]
If logged into a wallet that _did not vote_ the dapp shows an error rather than no vote commited.
![image](https://user-images.githubusercontent.com/12886084/88189795-bd56b580-cc39-11ea-8bc8-885477962c5b.png)

Also, clicking on display stats does not work, properly due to the same error in the console
![image](https://user-images.githubusercontent.com/12886084/88189852-d19ab280-cc39-11ea-8df6-dbd703b797c1.png)

**Comment by nicholaspai** [comment]
Looks like the subgraph actually changed haha I'll make a fix right now
