### ISSUE TITLE
Liquidation bot liquidates position that has been closed

### ISSUE THREAD

**Issue by daywiss** [UMAprotocol/protocol#1787]
**Description**

Liquidator bot liquidated a closed position. 

**Reproduction**
Might be difficult to reproduce, seems like it would only happen under certain circumstances

courtesy of @mrice32 
> Looks like they had 5 ETH collateralizing 500 yUSD, which is pretty well collateralized I think
> We queried their tokens outstanding
> then (slightly later) we queried their collateral using a separate call
> And the redemption transaction probably got sandwiched in between (edited) 

> Looks like they closed their position here: https://etherscan.io/tx/0x485d54eae8a16f6e9b732b63ee68c456b96df0ecba82dd2ff3a2e37e590dd028

**Expected Behavior**

Bot should not try to liquidate position.

**Version and OS Info**

Production bot usdeth-mainnet-liquidator

**Additional Context**

```
[error] usdeth-mainnet-liquidator (Liquidator)⭢Failed to liquidate position:rotating_light:
• error: Error: Transaction has been reverted by the EVM:
{
 "blockHash": "0xa7ef67e4ac1b01a70ba83c5a0f62f913aefccd6b0cb884736167990af293d578",
 "blockNumber": 10550941,
 "contractAddress": null,
 "cumulativeGasUsed": 897714,
 "from": "0x428ab2ba90eba0a4be7af34c9ac451ab061ac010",
 "gasUsed": 68552,
 "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
 "status": false,
 "to": "0xb56c5f1fb93b1fbd7c473926c87b6b9c4d0e21d5",
 "transactionHash": "0x25e2a064e1c288b16d575c04eead1e9edf68be46b78330925ebeee0003c784bf",
 "transactionIndex": 15,
 "events": {}
}
   at /protocol/node_modules/truffle/build/webpack:/node_modules/web3-core-method/src/index.js:364:1
   at runMicrotasks (<anonymous>)
   at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
```
 $(npm bin)/truffle exec --network test ./scripts/DecodeTransactionData.js --data 0x25ed4dd800000000000000000000000098d539ae90481e921fd9fb826500f2af063375550000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d9d40ea28843e00000000000000000000000000000000000000000000001b1ae4d6e2ef500000000000000000000000000000000000000000000000000000000000005f20b359
> Warning: possible unsupported (undocumented in help) command line option: --data
Using network 'test'.
Your decoded transaction information:
{
    "name": "createLiquidation",
    "params": {
        "sponsor": "0x98D539aE90481E921fd9fb826500F2aF06337555",
        "minCollateralPerToken": {
            "rawValue": "0"
        },
        "maxCollateralPerToken": {
            "rawValue": "3832076829230142"
        },
        "maxTokensToLiquidate": {
            "rawValue": "500000000000000000000"
        },
        "deadline": "1595978585"
    }
}
```

**Comment by nicholaspai** [comment]
As discussed, a possible issue is that the liquidator uses the return values of two contract queries in succession, `positions(sponsor)` and `getCollateral(sponsor)`, to determine whether to liquidate a position. We could remove the slight possibility that these calls reflect different contract state by explicitly setting the block number that we query from the latter `getCollateral()` call.

[Querying position state link](https://github.com/UMAprotocol/protocol/blob/master/financial-templates-lib/clients/ExpiringMultiPartyClient.js#L104)
[contract call "defaultBlock" optional param](https://web3js.readthedocs.io/en/v1.2.9/web3-eth-contract.html#methods-mymethod-call)

**Comment by chrismaree** [comment]
The default block is a good solution to this. we use similar logic in the LM scripts to query values at a given block number. with the free and non-archival Infura accounts you can query blocks up to 30 mins in the past, which should be fine for this use case.
