### ISSUE TITLE
Liquidator Bots OneInch Integration

### ISSUE THREAD

**Issue by kendricktan** [UMAprotocol/protocol#1804]
**Why**
Makes the bots more capital efficient in liquidating larger positions.

This means that the bots will be holding some stablecoin / common asset class e.g. `ETH/DAI/USDC` and will be attempting to convert them into the [tokenCurrency](https://github.com/UMAprotocol/protocol/blob/c6565ade08225d43563f91757f2df52c700d2dd2/core/contracts/financial-templates/expiring-multiparty/PricelessPositionManager.sol#L66) through OneInch.

**How**
- Things to add in `OneInchExchange.js`

Currently the swap function:

```javascript
async swap({ fromToken, toToken, amountWei }, options = {})
```

doesn't have a way to specify for a minum number of tokens to be returned The required change would become:

```javascript
async swap({ fromToken, toToken, minReturnAmountWei, amountWei }, options = {})
```

Additionally, we would need to include a function to provide us with an estimate on the `expectedReturn`, e.g.

```javascript
async getExpectedReturn({ fromToken, toToken, amountWei }, options = {})
```

In the event that the `returnAmount` does not meet the `minReturnAmountWei` requirements, an error will be thrown.

- Things to add to `ExpiringMultiPartyClient.js`

Currently the liquidation bot doesn't know what the address of the `tokenCurrency` is, the EMPClient should add the following method:

```javascript
async getTokenCurrency() {
    const tokenCurrencyAddress = await this.emp.methods.tokenCurrency().call({}, this.latestBlock)
    return new web3.eth.Contract(erc20Abi, tokenCurrencyAddress);
}
```

- Things to consider: market liquidity / slippage

We want to make sure that the swap from `ETH/DAI/USDC` to the `tokenCurrency` on 1inch is performed within a reasonable slippage. A new env variable e.g. `SWAP_MAX_SLIPPAGE` is needed. The logic for swapping the tokens will then be inserted into the following logical scope in `Liquidator.js`:

```javascript
// Simple version of inventory management: simulate the transaction and assume that if it fails, the caller didn't have enough collateral.
const notEnoughCollateral = liquidation.call({ from: this.account }).then(() => false).catch(() => true)

// Attempts to swap some capital for tokenCurrency
// Mutates the state of notEnoughCollateral in this logical scope
if (notEnoughCollateral) {
    // Max slippage as defined by user, defaults to 0
    // this.MAX_SPLIPPAGE = this.toBN(this.toWei(parseFloat(process.env.MAX_SLIPPAGE || 0))

    const tokenCurrency = await this.empClient.getTokenCurrency();
    
    // Will be in list form above
    for (const hotWalletAsset of ["ETH", "DAI", "USDC"]) {
       // Do a reverse calculation to estimate how much capital we need to get the amount of `tokensToLiquidate`
       // on 1inch
       const hotWalletAssetAmountWeiNeeded = oneInch.getExpectedReturn({ fromToken: tokenCurrency.address, toToken: hotStorageAsset, amountWei: tokensToLiquidate })

       // Is `price` the ratio of 1 tokenCurrency <-> <x> Collateral?
       // Make sure slippage isn't too big
       if (hotWalletAssetAmountWeiNeeded < (tokensToLiquidate * price) * (1 + this.MAX_SLIPPAGE)) {
           this.logger.debug('Slippage too big....');
           continue;
       }
       
       
       // If we have enough assets to get  `tokensToLiquidate` we swap, and set notEnoughCollateral = false
       if (hotWalletAsset.balanceOf(botAddress) > hotWalletAssetAmountWeiNeeded) {
            await oneInch.swap({ fromToken, toToken, minAmountReturnWei, amountWei })
            notEnoughCollateral = false
            break
       }
    }
}

// Now if notEnoughCollateral is still true, then continue
if (notEnoughCollateral) {
    logger.error('...')
    continue;
}
```

**Resolution**

Stuff specified in the **How** and some additional tests/mocks to ensure the logic is working properly

**Difficulty Score [1-10]**

5 days

**Comments**
> The smart contracts should disallow this, but a/o June 2020 this behavior is allowed so we should block it

This was found in the comments of `liquidator.js`, what does it mean?

Let me know what you think!

**Comment by nicholaspai** [comment]
> This was found in the comments of liquidator.js, what does it mean?

The full comment is:

```

      // If `tokensToLiquidate` is 0, then skip this liquidation. Due to the if-statement branching above, `tokensToLiquidate == 0`
      // is only possible if the `positionTokensAboveMinimum == 0` && `maxTokensToLiquidate < position.numTokens`. In other words,
      // the bot cannot liquidate the full position size, but the full position size is at the minimum sponsor threshold. Therefore, the
      // bot can liquidate 0 tokens. The smart contracts should disallow this, but a/o June 2020 this behavior is allowed so we should block it
      // client-side.
```

Explaining that liquidations for 0 tokens are technically allowed by the contracts but should be blocked as they would be meaningless transactions and would waste the user's gas.

**Comment by kendricktan** [comment]
Some clarification on the `price` (obtained from the `this.priceFeed.getCurrentPrice()`), what is it representative of?

Is it the ratio between `1 tokenCurrency <> X collateral`?

**Comment by nicholaspai** [comment]
> Some clarification on the `price` (obtained from the `this.priceFeed.getCurrentPrice()`), what is it representative of?
> 
> Is it the ratio between `1 tokenCurrency <> X collateral`?

Correct

**Comment by chrismaree** [comment]
This proposal seems pretty great to me! 

A few comments: 
1) The collateral currency will not _strictly_ be the same currency we want to trade from as the bot's reserve. You've included this in your proposal but I think it's important to note. Take yUSD, for example. The collateral type is WETH but we might want the liquidators to hold USDC which can then be converted into yUSD via 1inch for liquidations. My point here is that I think there needs to be a clear distinction between _collateral currency_ and liquidator _reserve currency_.

2) I think that this logic should sit _outside_ of the liquidator bot. If the bot in the `if (notEnoughCollateral) {` logic is hit it should call a separate module that is responsible for buying the collateral on 1inch. This separation of concerns will become particularly important when we want to enable the bots to also open a position.

**Comment by kendricktan** [comment]
> The collateral currency will not strictly be the same currency we want to trade from as the bot's reserve. You've included this in your proposal but I think it's important to note. Take yUSD, for example. The collateral type is WETH but we might want the liquidators to hold USDC which can then be converted into yUSD via 1inch for liquidations. My point here is that I think there needs to be a clear distinction between collateral currency and liquidator reserve currency.

I like the word `reserve`! I've been reading up more on the quanto/compo products and will update the proposal sometime tomorrow.

> I think that this logic should sit outside of the liquidator bot. If the bot in the if (notEnoughCollateral) { logic is hit it should call a separate module that is responsible for buying the collateral on 1inch. This separation of concerns will become particularly important when we want to enable the bots to also open a position.

Which piece of logic are you referencing in particular?

**Comment by mrice32** [comment]
I really like the way you're parameterizing slippage -- I think it's the right way to go.

Note: this is definitely a future optimization, just wanted to think out loud in this thread. I was thinking a little more about ensuring profitability and wondering if it's possible to use 1inch to estimate if it's profitable to go from reserve currency -> 1inch -> synthetic token -> liquidation -> collateral currency -> 1inch -> reserve currency.

**Comment by nicholaspai** [comment]
Additional change: `Swap` should only be called after checking explicitly that the liquidator bot does not have enough tokens to execute the liquidation:

```js
// Simple version of inventory management: simulate the transaction and assume that if it fails, the caller didn't have enough collateral.
const notEnoughCollateral = liquidation.call({ from: this.account }).then(() => false).catch(() => true)
```

This code is too general and potentially will catch false positives such as the liquidator not having enough allowance. A better check would be 

```js
const notEnoughTokens = tokenCurrency.balanceOf(liquidator).lt(tokensToLiquidate)
```

Note also that `notEnoughCollateral` should be more accurately renamed to `notEnoughTokens` or `notEnoughSynthetic`
