### ISSUE TITLE
Find reliable method for verifying contracts on Etherscan

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#1807]
**Why**

We've repeatedly had issues deploying via truffle and using truffle flattener to verify the contracts on etherscan. We should find a new pipeline that reliably works.

**How**

I think either a new flattening or a new deployment method will be required.

**Resolution**

Contracts are verified either programmatically or manually, but with an obvious, always-working process.

**Difficulty Score [1-10]**

6: ~1 day or 7: ~3 days (rough estimate, lots of uncertainty)

**Comment by adrianmcli** [comment]
Turns out @kendricktan was working on this exact issue at Omisego (he's their devops lead after all) and seems to have an understanding of why verifying doesn't work sometimes. So maybe @kendricktan you can share your analysis of the actual problem?

**Comment by adrianmcli** [comment]
Tagging @chrismaree here as well.

**Comment by kendricktan** [comment]
@mrice32 @chrismaree 

Verifying contracts on etherscan has been more of a horror story for me.

I've made an [example repository showcasing how slight changes to the contracts location/headers can lead to different generated bytecode](https://github.com/kendricktan/etherscan-verification-horrors). The example repository uses the `solc` binary to compile the contracts, and not via a build-tool, so the effects should be seen by every build-tool that uses `solc`.

### Findings

#### 1. Contract directory location affects generated bytecode

This is likely because of the [contract metadata](https://solidity.readthedocs.io/en/v0.6.7/metadata.html) inside `solc`. For example, the bytecode generated from compiling identical contracts `ContractA` from `./contracts/ContractA` and from `./contracts/inner-directory/ContractA` will be different.

This **in theory** should not be too much of a issue because [swarm hashes should not affect (in most cases) etherscan contract verification](https://github.com/trufflesuite/truffle/issues/456#issuecomment-370133955)

#### 2. `pragma experimental ABIEncoderV2` affects generated bytecode

This might explain why some of the flattened contract source code differs from the deployed bytecode, as some sections of the contract might not be using `pragma experimental ABIEncoderV2`.

When you flatten them, you are forcing the `ABIEncoderV2` feature onto them.

#### 3. `pragma experimental ABIEncoderV2` inserted location affects generation bytecode

This could be related to the [contract metadata](https://solidity.readthedocs.io/en/v0.6.7/metadata.html), might be something we need to keep in mind.

#### Next Steps
Given the amount of things that can affect the generated bytecode, perhaps the most consistent way for verifying would be to:

1. Flatten the to-be-deployed contract along with its imports into a single file
2. Compile the flatten contract and then deploy respective contract.

What do you guys think?

**Comment by nicholaspai** [comment]
@kendricktan Even after fixing the ABIEncoderV2 issues, I've still run into mysterious errors. The one process that has worked in the past is to the compile the flattened contract (after fixing the pragma errors as you list above) in [remix](https://remix.ethereum.org/), deploy via Remix, and use that ABI/bytecode to verify the contracts.

If there's a way to see the Remix source code or dynamically leverage it, this might be the best strategy

**Comment by adrianmcli** [comment]
@nicholaspai looks like this is the code Remix uses for compiling: https://github.com/ethereum/remix/blob/master/remix-solidity/src/compiler/compiler.ts

They're using `solc`: https://github.com/ethereum/remix/blob/master/remix-solidity/src/compiler/compiler-worker.ts#L3

We can do this, but it means we'd no longer be using Truffle to compile.

**Comment by mrice32** [comment]
@kendricktan I think this is really solid analysis -- +1!

> Verifying contracts on etherscan has been more of a horror story for me.

Same. The sensitivity of the compilation system to minute and non-logic-related details has always been quite worrisome to me.

> When you flatten them, you are forcing the ABIEncoderV2 feature onto them.

Does this only apply to code that sits _below_ the ABIEncoderV2 declaration or does it affect all code in the file? If it's the former, it might work to just move all of the contracts that had ABIEncoderV2 declared in them below the declaration and move those that didn't above the declaration. Although, that may be just as hard as pre-flattening the files before compilation 🤷.

> 1. Flatten the to-be-deployed contract along with its imports into a single file
> 2. Compile the flatten contract and then deploy respective contract.

Yeah, I think this makes sense. Mimicking the exact source that Etherscan sees is probably prudent if we want our compilation system to match consistently, even if it is a little strange to flatten in the local compilation process. This could be why we've seen Remix work.

I do have one final piece of confusion, however. Etherscan has a multi-file upload verification, where you can upload many files that import one another and it will compile them that way. This should **in theory** almost exactly match what we're doing locally. However, I've found that even _that_ fails to match sometimes (although it has also fixed the problem on occasion too). The difference here may be caused by the metadata differences you mentioned in 1 since the directory structure changes to one single flattened directory. Note: when using this method, you do have to rework the imports so they work in a flat dir rather than our directory structure (we wrote a quick-and-dirty script to do this).

That context aside, I think a good testing ground to ensure the flattening method you have proposed will work is compiling a pre-flattened`Voting.sol`, `ExpiringMultiPartyCreator.sol`, and `ExpiringMultiPartyLib.sol` and seeing if they all verify successfully. Then, as a final test, we should ensure that an `ExpiringMultiParty.sol` contract deployed using [this ExpiringMultiPartyCreator method](https://github.com/UMAprotocol/protocol/blob/370a635232a4d5f73e2548999b989fa162771a9e/core/contracts/financial-templates/expiring-multiparty/ExpiringMultiPartyCreator.sol#L66) can be verified (`core/scripts/local/DeployEMP.js` will probably be helpful here).

Thoughts?

**Comment by kendricktan** [comment]
@nicholaspai 

> If there's a way to see the Remix source code or dynamically leverage it, this might be the best strategy

Remix uses `solcjs` under the hood, which is javascript bindings for `solc` :smiley: 

> Does this only apply to code that sits below the ABIEncoderV2 declaration or does it affect all code in the file? If it's the former, it might work to just move all of the contracts that had ABIEncoderV2 declared in them below the declaration and move those that didn't above the declaration when trying to verify. Although, that may be just as hard as pre-flattening the files before compilation

It seems like it'll affect all code in the file. [In the example repo, the generated bytecode from contracts A, and D](https://github.com/kendricktan/etherscan-verification-horrors) differs quite significantly in structure (more than just a swarm hash difference). For context, Contract D is basically Contract A, but with `pragma experimental ABIEncoderV2` appended **at the bottom**.

> I do have one final piece of confusion, however. Etherscan has a multi-file upload verification, where you can upload many files that import one another and it will compile them that way. This should in theory almost exactly match what we're doing locally. However, I've found that even that fails to match sometimes (although it has also fixed the problem on occasion too). The difference here may be caused by the metadata differences you mentioned in 1 since the directory structure changes to one single flattened directory. Note: when using this method, you do have to rework the imports so they work in a flat dir rather than our directory structure (we wrote a quick-and-dirty script to do this).

Sounds like a horror story :stuck_out_tongue: 

> That context aside, I think a good testing ground to ensure the flattening method you have proposed will work is compiling a pre-flattenedVoting.sol, ExpiringMultiPartyCreator.sol, and ExpiringMultiPartyLib.sol and seeing if they all verify successfully. Then, as a final test, we should ensure that an ExpiringMultiParty.sol contract deployed using this ExpiringMultiPartyCreator method can be verified (core/scripts/local/DeployEMP.js will probably be helpful here).

Sounds good!

**Comment by kendricktan** [comment]
A bit of an update. Without any additional scripts, I've managed to verify the contracts [ExpiringMultiPartyCreator](https://kovan.etherscan.io/address/0x2bc9485Ea587Ac7A9b9e2747555DD37c36466ea1#code) and [Voting](https://kovan.etherscan.io/address/0x24BE89E098d6F65A924142d93013A84281F6296B#code) on etherscan.

## Steps
Without any additional config, in the core directory
1. `npx buidler compile`
2. There should be a new file in `core/cache` which contains the standardized input method for solidity, `solc-input.json`
3. Edit `solc-input.json` and make sure its using whatever runs truffle is (199 at this time of writing), and add in the following to the `settings` key:

```javascript
"settings": {
    ...
    "libraries": {
      "contracts/financial-templates/expiring-multiparty/ExpiringMultiPartyLib.sol": {
        "ExpiringMultiPartyLib": "0xB6693A4cB6CFd70680145e733388C7FE8b778841" // ExpiringMultiPartyLib deployed address
      }
    },
    ...
  }
```

4. Verify contracts using etherscan's Standard-Json-Input
![Screenshot-2020-08-12-16:17:50](https://user-images.githubusercontent.com/9071748/89981552-6764b300-dcb7-11ea-9f93-ca0201ab2ceb.png)

**Comment by nicholaspai** [comment]
@kendricktan Is there an easy way to determine the ABI-encoded constructor arguments passed into contracts? Or do we just use an [external tool](https://abi.hashex.org/)

**Comment by kendricktan** [comment]
@nicholaspai iirc etherscan automatically finds the ABI-encoded constructor agrs for you.
