### ISSUE TITLE
Explain high quota usage in Cloud Run bot environment

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#1809]
**Why**

The Cloud Run bots seem to use a significant amount of quota compared to the looping bots.

**How**

Compare and examine the calls directly.

**Resolution**

An explanation (and possibly a fix) should be added to this issue.

**Difficulty Score [1-10]**

6: ~1 day

**Comment by chrismaree** [comment]
This issue has been addressed spanning a number of Pull requests. Main improvements can be grouped as follows:
- optimizing execution logic to better handle parallel calls and use `Promise.all` through the bots: [PR1](https://github.com/UMAprotocol/protocol/pull/1813) [PR2](https://github.com/UMAprotocol/protocol/pull/1829) [PR3](https://github.com/UMAprotocol/protocol/pull/1837) [PR4](https://github.com/UMAprotocol/protocol/pull/1873)
- Refactoring bots to run without truffle. This improved a bunch of execution logic as truffle has a lot of overhead. [PR1](https://github.com/UMAprotocol/protocol/pull/1856) [PR2](https://github.com/UMAprotocol/protocol/pull/1890) [PR3](https://github.com/UMAprotocol/protocol/pull/1891)
- Adding re-try logic to bots so they don't need to re-run all long if there is execution error: [PR1](https://github.com/UMAprotocol/protocol/pull/1838) [PR2](https://github.com/UMAprotocol/protocol/pull/1867)
