### ISSUE TITLE
Add retry logic to all bots

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#1812]
**Why**

Bots crash occasionally due to price feed or infura errors. The bot should automatically retry the run `n` times before crashing and notifying a human.

**How**

A wrapper should be written to automatically catch errors and ignore them unless it's the `n`th time.

**Resolution**

The bots should be retrying on error rather than crashing.

**Difficulty Score [1-10]**

5: ~4 hours

**Comment by chrismaree** [comment]
This issue is linked to #1714 as well.
