### ISSUE TITLE
Coverage is flaky in ci

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#1854]
**Description**

Coverage (and buidler tests generally) sometimes seem to hang for a while after the tests are complete. It's unclear whether it just hangs for a long time or if it hangs _indefinitely_. Either way, circleci terminates the run if there are no log messages for over 10 minutes. This termination is causing the coverage runs to fail occasionally.

Example: https://app.circleci.com/pipelines/github/UMAprotocol/protocol/7877/workflows/b85e3bee-c7bb-48c7-b4fe-3d1c101ffd6e/jobs/57199.

**Reproduction**

This can be reproduced by running coverage in ci multiple times.

It's unclear whether this can be reproduced locally.

**Expected Behavior**

Coverage should not hang for >10 minutes with no log messages. If this is just an artifact of using buidler (and the process will complete after > 10 minutes), we should either extend the timeout or swap to using truffle to run the coverage tests. Note: the runtime for buidler vs truffle coverage seems to be similar if not slower with buidler, unlike the non-coverage tests.

**Screenshots**

N/A

**Version and OS Info**

N/A

**Comment by kendricktan** [comment]
Lets just use truffle for coverage if the runtime is similar
