### ISSUE TITLE
Add script to compute a voting gas refund in terms of UMA tokens

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#1874]
**Why**

To refund users for their voting gas expenditures.

**How**

The script should compute the average UMA/ETH price during the commit period and the reveal period and use that to compute how much each voter needs in $UMA after the vote.

Voters who do not commit _and_ reveal should not get a refund.

**Resolution**

Self-explanatory.

**Difficulty Score [1-10]**

7: ~3 days

**Comment by nicholaspai** [comment]
Closed by #1936
