### ISSUE TITLE
Build PositionManager

### ISSUE THREAD

**Issue by nicholaspai** [UMAprotocol/protocol#2016]
**Summary**

This contract will enable position management features for a perpetual contract sponsor. Features to include:
- **create**: create debt, add collateral if neccessary
- **deposit**: add collateral
- **withdraw** (fast + slow): withdraw collateral
- **redeem**: burn debt, withdraw collateral
- **repay**: pay back debt

The perpetual contract should continuously apply a funding rate to incentivize arbitrageurs to bring the synthetic price back to the index's.

New production contracts to write:
- `PositionManager`
- `FundingRateApplier`

**Implementation**

Proposed construction parameters must also be set up:
```
constructionParams: {
        uint256 _withdrawalLiveness, // Liveness delay, in seconds, for pending withdrawals.
        address _collateralAddress, // ERC20 token used as collateral for all positions.
        address _fpFinderAddress, // Finder pointing to financial-product related contracts
        address _dvmFinderAddress, // Finder pointing to oracle related contracts
        bytes32 _priceIdentifier, // Registered identifier in the DVM for the synthetic.
        string memory _syntheticName, // ERC20 Name for the token contract that will be deployed.
        string memory _syntheticSymbol, // ERC20 symbol for the token contract that will be deployed.
        FixedPoint.Unsigned memory _minSponsorTokens, // Minimum amount of collateral that must exist at any time in a position.
        address _timerAddress, // Contract that stores the current time in a testing environment.
        address _excessTokenBeneficiary // Beneficiary to which all excess token balances that accrue in the contract can be forwarded to
}
```

**Differences from EMP**
- new `repay` method
- no `expirationTimestamp` construction param because there is no longer an expiry process
- removed `tokenFactoryAddress` construction param in favor of pointing to it in the `fpFinder`.
- similar to the `FeePayer` contract which modifies sponsor positions based on an ongoing regular fee charge, there will be a new `FundingRateApplier` contract that modifies the value of synthetic token debt based on an ongoing funding rate. For the `PositionManager`, this funding rate will come into effect for emergency shutdowns only, but the rate should be updated on every contract call.

***Finders***
Finders facilitate upgradeability by allowing community and devs to switch out protocol contracts by replacing finder pointers instead of unnecessarily redeploying core contracts.
- `fpFinder`: points to financial-contract related addresses: `TokenFactory`, `FundingRateStore`
- `dvmFinder`: points to oracle related addresses: `IdentifierWhitelist`, `Oracle`, `FinancialContractsAdmin`

***Emergency Shutdown***
Emergency shutdowns are used by the Governor to prematurely end a financial contract under emergency circumstances. In the expiring contract, the emergency shutdown is implemented as a premature expiration. Without expiry settlement, this implementation will have to be slightly different for the perpetual. I propose flipping a new state boolean variable `isEnded` via the `emergencyShutdown()` method, and blocking all contract actions when `isEnded === true`.

***Repay***
This should combine the functionality of `redeem()` and `deposit()`.
- Transfers-in: `uint256 amountToRepay`
- Transfers-out: None

***Apply Funding Rates***
- Every contract call should update `FundingRateApplier`'s rate, similar to how a regular fee is updated one very contract interaction.

**How**

Most of this can be borrowed from the EMP's PPM. New logic is fetching the funding rate and applying it to modify sponsor debt.

**Resolution**

Unit tests should be made using hard coded funding rates.

**Difficulty Score [1-10]**

- 8: ~1 week

**Comment by chrismaree** [comment]
Should the `applyFundingRate` modify sponsor debt as a function call or should this rather be more akin to the `_getFeeAdjustedCollateral` from the EMP that considers the cumulative fees in this value? Put another way, the funding rate should be applied directly to all sponsor debt without needing a specific function call?

**Comment by chrismaree** [comment]
Follow up question: what solidity version should we start building this on? Solidity 7.1 is out now so we could consider upgrading to this for these new contracts.

**Comment by chrismaree** [comment]
Also should the constructor not include the `fundingRateStoreAddress` address?

**Comment by daywiss** [comment]
> Should the `applyFundingRate` modify sponsor debt as a function call or should this rather be more akin to the `_getFeeAdjustedCollateral` from the EMP that considers the cumulative fees in this value? Put another way, the funding rate should be applied directly to all sponsor debt without needing a specific function call?
> 
> If I understand correctly from the PRD `applyFundingRate` calls funding rate store's `getCurrentFundingRate()` to get the current rate and does the math internally to apply funding rate to the contract. So perhaps the wording in this issue should be slightly modified to align with the PRD.

I imagined this being applied to all positions in a single call. I dont think there should be a public call which only applies funding rate to a specific position.

**Comment by nicholaspai** [comment]
> Should the `applyFundingRate` modify sponsor debt as a function call or should this rather be more akin to the `_getFeeAdjustedCollateral` from the EMP that considers the cumulative fees in this value? Put another way, the funding rate should be applied directly to all sponsor debt without needing a specific function call?

I think your sense that this shoud be called internally on every function call is correct. ASSUMING the gas is not too high.

**Comment by nicholaspai** [comment]
> What solidity version should we start building this on? Solidity 7.1 is out now so we could consider upgrading to this for these new contracts. Or should we keep it at 0.6.12 to keep thins standard?

I think we should keep it standard to have it work with our verification scripts, unless 7.1 has some strong features we want to take advantage of

**Comment by nicholaspai** [comment]
> Also should the constructor not include the `fundingRateStoreAddress` address?

Great point. I think to maximize upgradeability, we should have some sort of Finder-esque contract that stores both the `fundingRateAddress` and the `tokenFactoryAddress`. I don't think these should naively be in the `Finder` because the `Finder` was designed to be an Oracle related contract.

**Comment by nicholaspai** [comment]
@chrismaree I've updated the issue description to distinguish between a `dvmFinderAddress` and a `fpFinderAddress`, the latter I'm thinking can point to a TokenFactory and a FundingRateStore

**Comment by mrice32** [comment]
- Use modifier to update the funding rate on collateral-modifying calls.
- Rip out settlement logic.
- Add in emergency-shutdown specific logic.
- Repay function (redeem + deposit).
