### ISSUE TITLE
Build Liquidatable

### ISSUE THREAD

**Issue by nicholaspai** [UMAprotocol/protocol#2024]
**Summary**

This contract will enable a position managers' sponsors to be liquidated and for those liquidations to be disputed.

Unlike the expiring contract, the perpetual contract should incorporate a funding rate multiplier in its token redemption value (TRV) calculations. Note that a TRV can only be derived after a DVM vote resolution since it relies on an external price.

New production contracts to write:
- `Liquidatable`

**Implementation**

Proposed construction parameters must also be set up:
```
constructionParams: {
       ...All params from PositionManager,
        uint256 liquidationLiveness, // Pending liquidation time before expiry
        FixedPoint.Unsigned collateralRequirement, // Required collateral:TRV ratio for a sufficiently collateralized position
        FixedPoint.Unsigned disputeBondPct, // % of locked collateral to be deposited by a disputer
        FixedPoint.Unsigned sponsorDisputeRewardPct, // % of TRV paid to sponsor following successful dispute
        FixedPoint.Unsigned disputerDisputeRewardPc, // % of TRV paid to disputer following successful dispute
}
```

**Differences from EMP**
- TRV calculation in `_settle` should incorporate the `FundingRateMultiplier`'s current multiplier.
- no expiry logic
- Funding rate multiplier's current rate should be updated on every contract call.

***Apply Funding Rates***
- Every contract call should update `FundingRateApplier`'s rate, similar to how a regular fee is updated one very contract interaction.

**How**
Most of this can be borrowed from the EMP's PPM. New logic is fetching the funding rate and applying it to modify sponsor debt.

**Resolution**

Unit tests should be made using hard coded funding rates.

**Difficulty Score [1-10]**

- 8: ~1 week

**Comment by mrice32** [comment]
- Apply funding rate adjustment to price.
- Remove modifiers that reference settlement or expiration.

**Comment by mrice32** [comment]
Closing in favor of specific issues for the two bullets above^
