### ISSUE TITLE
Priceless Perpetual Contract Phase 1

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#2029]
The goal is to create a protocol enabling smart contracts that allow users to deposit and maintain collateral to borrow non-expiring tokens tracking a specific price identifier. Sponsor positions are margined according to the index price, while funding rates take the synthetic’s price into consideration as well.

The unique goal of this particular perpetual instrument is to be “priceless”: it should make minimal price requests and its incentive design should instead encourage stakeholders to report accurate funding rates that will encourage the synthetic to track the price identifier. This would stand in contrast to existing perpetual instruments that depend upon trusted funding rate reporters.

**Comment by mrice32** [comment]
Closing in favor of specific tasks to build a perpetual contract in the Evergreen Project.
