### ISSUE TITLE
Build Funding Rate Applier

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#2030]
**Summary**

This contract reads funding rates from a `FundingRateStore` and uses it to continuously update a funding rate multiplier, `cumulativeFundingRateMultiplier`, state variable, similar to how `FeePayer.sol` keeps track of `cumulativeFeeMultiplier` to assess regular fees. The `cumulativeFundingRateMultiplier` comes into play on emergency shutdowns, liquidations, and disputes by modifying token redemption value (TRV).

A `PositionManager` or `Liquidatable` that wants to assess funding rates on TRV should import this contract.

New production contracts to write:
- `FundingRateApplier`

**Implementation**

Proposed construction parameters must also be set up:
```
        ...TBD,
        uint _initialFundingRate, // Starting funding multiplier, e.g. 1.1, 1.0, 0.9, etc.
        address _fpFinderAddress, // fetch financial-product related contracts
        address _timerAddress, // Testable timing contract

```

***Financial Product Finder***
This should point to a `FundingRateStore` that returns the current funding rate, which this contract can use to update its `cumulativeFundingRateMultiplier` value.

**Interface**
- A modifier `updateFunding` should be exposed so that client contracts such as `PositionManager` can update the funding rate multiplier on each contract call based on the funding rate store's latest funding rate.
- `pfc()` should be updated to reflect funding rate effects on profit from corruption.
- Internal methods should be exposed that return the TRV of a synthetic token unit given an oracle price and the current `cumulativeFundingRateMultiplier` value.

**How**

This should be modeled after `FeePayer` in that the `PositionManager` should inherit it, but it will probably be substantially different.

**Difficulty Score [1-10]**

- 8: ~1 week

**Comment by chrismaree** [comment]
I've started looking into the implementation of this issue and am not sure about why we need to consider the `pfc` for the funding rate applier. Specifically, the PFC in the current EMP defines _the profit from corruption for this contract in terms of the collateral currency_. The funding rate applier specifically modifies synthetic debt balances and does not modify the collateral and so I'm not sure why we need to consider it here.

If the funding rate applier was to have a pfc function then would we not need to consider the pfc as the sum of profit from corruption from collateral currency & synthetic debt (which is different from our current definition)?

**Comment by nicholaspai** [comment]
> I've started looking into the implementation of this issue and am not sure about why we need to consider the `pfc` for the funding rate applier. Specifically, the PFC in the current EMP defines _the profit from corruption for this contract in terms of the collateral currency_. The funding rate applier specifically modifies synthetic debt balances and does not modify the collateral and so I'm not sure why we need to consider it here.
> 
> If the funding rate applier was to have a pfc function then would we not need to consider the pfc as the sum of profit from corruption from collateral currency & synthetic debt (which is different from our current definition)?

This is a good point. With the current cToken style of implementing the funding rate I agree with your intuition that this will not modify the PfC.
