### ISSUE TITLE
disable 1-inch integration in liquidator bot in favor of withdraw defense strategy

### ISSUE THREAD

**Issue by daywiss** [UMAprotocol/protocol#2056]
**Why**
The 1inch integration in liquidator bot allows the bot to hold collateral and efficiently turn it into synthetic on the open market at time of liquidation. After working through the withdraw defense strategy, certain problems with the implementation are coming to light, and I would recommend disabling it in the short term to allow for a refactor later.

The issues are quite subtle but on a conceptual level there are also incompatibilities with the withdraw defense strategy. 
- 1inch integration buys just enough tokens to liquidate position fully, defense strategy requires that you save some tokens for withdraw extension fund. meaning there are 2 different visions of how bot balance should be managed, as well as how positions should be liquidated. This means defense strategy cannot just run after 1inch calls, and vice versa.
- defense strategy triggers when synthetic token balance is insufficient to fully liquidate position, but with one inch integration synthetic balance may be 0 until funds are purchased, rendering defense strategy unable to calculate a liquidation size.
- @mrice32 pointed this out, but 1inch integration does not correctly calculate the amount of tokens to buy, even with the collateral available to buy synthetics to fully liquidate it may always partially liquidate.
- When liquidating multiple positions, the current tokensToLiquidate logic overestimates your synthetic balance causing a liquidation to error rather than partial liquidation.  This should be replaced by the defense strategy implementation which fixes this problem.

1inch integration currently is not used in production, and probably shouldn't be until we can address these technical issues and other design issues around how to more robustly add it. 

**How**
- Deprecate usage of 1inch by logging a warning or throwing an error if configuration would enable it
- Move current 1inch logic into a standalone function which would do the collateral to synthetic conversion when called on
- update tests
- Revisit the full integration when the team feels this functionality needs to be automated 

**Resolution**
- See that 1inch logic is moved out of the `liquidatePositions` function and into a standalone function.
- See that there is visibility to the end user if they want to enable this feature that its no longer available (if needed)

**Difficulty Score [1-10]**
- 4: ~2 hours

**Comment by mrice32** [comment]
@daywiss I think this is a great proposal. I would say it's also acceptable just to remove the 1inch logic altogether if moving it to a standalone function is too annoying. It's always in the git history :)
