### ISSUE TITLE
Build FundingRateStore

### ISSUE THREAD

**Issue by nicholaspai** [UMAprotocol/protocol#2061]
**Why**

Funding Rate Store must return a current funding rate for a specified `fundingRateIdentifier`, and might also provide logic for updating the funding rate in a priceless manner.

**How**

Proposed interface:
- `getFundingRateForIdentifier(bytes id)`: Returns the latest funding rate for a `fundingRateIdentifier`. If this contract needs to request a price to the DVM (i.e. not a MockFundingRateStore), then the `fundingRateIdentifier` must be whitelisted.

Proposed construction params:
- `timerAddress`: Address of testable timing contract.
- `finderAddress`: Points to DVM-related contracts. This contract will need to request "prices" for funding rates.
- `proposeLiveness`: amount of time until a proposed funding rate is eligible to be published as the current funding rate
- `proposerRewardRate`: the percent per unit time that rewards accumulate for an eventual funding rate reporter.

Proposed additional methods:
- `proposeFundingRate`: enqueues a pending funding rate and resets the `proposeLivenessTimer`, fails if there is already a pending funding rate. **This should fail if the proposed funding rate is the same as the current funding rate.**
- `publishFundingRate`: if pending funding rate liveness has expired, then replaces the current funding rate with the pending funding rate, deletes the pending funding rate, and pays the original proposer a reward. If there is no pending funding rate that has expired, but there is a settled disputed funding rate, then sets the result of the dispute as the current funding rate. 
- `disputeFundingRate`: triggers a DVM request to resolve whether a pending funding rate was valid. Removes pending funding rate from queue. Disputer must post a bond.
- `calculateFundingRate`: Helper method for DVM voters, can pass in some data to compute what the store would calculate as the funding rate based on the data.

**Open questions**
- How does the store attain a treasury of reserves from which it can reward proposers? 
- How do you determine the amount of rewards to pay successful funding rate proposers? 
    - Should the rewards accrue over time (since the last update)? 
    - Should the rewards be proportional to the delta between the proposed funding rate and the current funding rate?
- What happens if store doesn't have "enough" rewards to pay a proposer?
- Upgradeability: is it is as simple as deploying a new Store and changing the pointer in the Finder?

**Difficulty Score [1-10]**

This is a measure of the amount of developer time this task will require to be completed. Note: this should include design and planning time in addition to implementation time. The scale is not linear:

- 8: ~1 week

**Comment by mrice32** [comment]
@nicholaspai @chrismaree I've started work on the funding rate store. Will start tackling sub-bugs. I'll communicate which ones I'm working on by self-assigning when I start.

**Comment by nicholaspai** [comment]
Replacing this with the Optimistic oracle from #2212
