### ISSUE TITLE
Disputer and Liquidator bots compare expirationTimestamp to contractTimestamp incorrectly

### ISSUE THREAD

**Issue by nicholaspai** [UMAprotocol/protocol#2068]
**Description**

[Liquidator](https://github.com/UMAprotocol/protocol/blob/master/packages/liquidator/index.js#L83) and [Disputer](https://github.com/UMAprotocol/protocol/blob/master/packages/disputer/index.js#L68) bots do not cast timestamps to numbers when checking if a contract has expired. 

This has worked in practice with realistic timestamps, for example:

```sh
> node
Welcome to Node.js v12.14.1.
> "1601996024" >= "1601996023"
true
```

But gives a false positive in the tests [here (disputer)](https://github.com/UMAprotocol/protocol/blob/master/packages/disputer/test/index.js#L145) and [here (liquidator)](https://github.com/UMAprotocol/protocol/blob/master/packages/liquidator/test/index.js#L148).

```sh
> node
Welcome to Node.js v12.14.1.
> "11345678900" >= "20345678900"
false
```

**Resolution**

Bots should cast timestamps to numbers before comparing, and tests need to be rewritten

**Comment by mrice32** [comment]
Haha, nice find @nicholaspai! I really think the comparison operators should just be disabled on strings at the language level because it's _almost_ never what you want to do (these operations could be turned into functions for strings or something).

**Comment by nicholaspai** [comment]
Yeah I think the way node.js compares strings is byte by byte, which is why it doesn't cause problems with real timestamps
