### ISSUE TITLE
Liquidatable: Dispurse dispute rewards in one transaction

### ISSUE THREAD

**Issue by nicholaspai** [UMAprotocol/protocol#2149]
**Why**

Currently the sponsor, liquidator, and disputer must withdraw their own rewards individually. We should just dispurse them on the first `withdrawLiquidatorRewards` call and anyone can call this. This might also reduce bytecode by eliminating local variables.

**Resolution**

This will impact unit tests and more importantly it might change the ABI for the following methods and events:
- `withdrawLiquidation(uint256 liquidationId, address sponsor) returns returns (FixedPoint.Unsigned memory amountWithdrawn)`
- `event LiquidationWithdrawn(
        address indexed caller,
        uint256 withdrawalAmount,
        Status indexed liquidationStatus,
        uint256 settlementPrice
    )`

On the first point, `withdrawLiquidation` should return a different amount, perhaps either the total amount withdrawn, or a tuple containing the three different reward payouts. The event `LiquidationWithdrawn` should also be modified to include more detailed breakdown of the payouts.

This will mean that bot code that uses the updated ABI's will break.

**Difficulty Score [1-10]**

This is a measure of the amount of developer time this task will require to be completed. Note: this should include design and planning time in addition to implementation time. The scale is not linear:

- 5: ~4 hours

**Comment by nicholaspai** [comment]
@mrice32 Looks like this is going to save ~400 bytes!

**Comment by mrice32** [comment]
Very nice!!
