### ISSUE TITLE
Fix flash swap vulnerability in funding rate store

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#2183]
**Why**

The use of pfc in the funding rate store makes the implementation and every function in the funding rate store associated with rewards vulnerable to a flash loan attack Specifically because the reward is a function of pfc, a flash swap can be used to increase the perp pfc during the withdrawal tx and to extract an unfair reward for proposing a funding rate. This is discussed here: https://github.com/UMAprotocol/protocol/pull/2168/files#r522300851

This attack would look as follows:

Propose a valid funding rate.
1) wait until liveness period has passed.
2) execute a transaction that does the following internal steps:
3.a) flash swap perp collateral currency.
3.b) create a small position, well above the GCR, collateralized with the flashswap'ed collateral. The larger the relative size of the flashswap to the total collateral in the contract the more profitable the attack.
3.c) withdraw your reward from the proposal. During this, the calculation of pfc is biased upwards from your collateral created during 3.b.
3.d) redeem position created in 3.b. This will return all flashloaned collateral
3.e) repay flashloan
4) profit

In a discussion with @nicholaspai there is a solution to this by enforcing that the last addition to contract pfc was done in a separate block to _publishRateAndWithdrawRewards being called. 

**How**

This flashswap vulnerability can be addressed by enforcing that the block the rewards are claimed is different from the last block the pfc was increased in the perp. This can be done by the perp informing the funding rate store whenever collateral is added to the perp (adding to the pfc) and then requiring that the block number that the funding rate proposer is claiming rewards is not equal to the last block. This can be done by adding a function & modifier to the `FundingRateApplier`.

**Resolution**

This vulnerability is fixed and tested.

**Difficulty Score [1-10]**
- 7: ~3 days

**Comment by nicholaspai** [comment]
More details on the proposed solution:

Add to `FundingRateStore.sol`:
- `uint256 lastPfcUpdateTimestamp` param in the `fundingRateRecords` struct for a particular perpetual address

Add to `FundingRateStoreInterface.sol`:
- `updatePfc()` updates the `lastPfcUpdateTimestamp` for the calling perpetual contract's. 

Add to `FundingRatePayer.sol`:
- A modifier that calls `FundingRateStoreInterface.updatePfc()`. This modifier should be added to any method that would be involved in a flash-loan "attack" to manipulate the `pfc()` reading from the FundingRateStore.

**Comment by mrice32** [comment]
As stated [here](https://github.com/UMAprotocol/protocol/pull/2168#discussion_r522430148), I don't think this is a vulnerability because I think there's a subtle flaw in the initial analysis (although I could be wrong, so please correct me!!).
> 3.d) redeem position created in 3.b. This will return all flashloaned collateral

I think this is incorrect. The collateral in your position will be proportionally docked, just like everyone else's. Let's do a simple example. Let's say the reward percentage is 10%, and there's $10MM in the contract. You flash loan another $10MM to double the size of the contract. In the non-flash loan case, the $1MM is paid out by the contract. In the flash loan case $2MM is paid out. However, that extra $1MM is coming out of _your position_. So, on redemption, you would only have 90% of your position left ($9MM) because the cumulativeFeeMultiplier had been changed to 90% of its previous value.

Thoughts? Do y'all agree with this analysis?

**Comment by nicholaspai** [comment]
> As stated [here](https://github.com/UMAprotocol/protocol/pull/2168#discussion_r522430148), I don't think this is a vulnerability because I think there's a subtle flaw in the initial analysis (although I could be wrong, so please correct me!!).
> 
> > 3.d) redeem position created in 3.b. This will return all flashloaned collateral
> 
> I think this is incorrect. The collateral in your position will be proportionally docked, just like everyone else's. Let's do a simple example. Let's say the reward percentage is 10%, and there's $10MM in the contract. You flash loan another $10MM to double the size of the contract (mint some tokens with $10MM worth of collateral). In the non-flash loan case, the $1MM is paid out by the contract. In the flash loan case $2MM is paid out. However, that extra $1MM is coming out of _your position_ (since you are now half of the contract's collateral)! So, on redemption, you would only have 90% of your position left ($9MM) because the cumulativeFeeMultiplier had been changed to 90% of its previous value.
> 
> Thoughts? Do y'all agree with this analysis?
> 
> cc @chrismaree @nicholaspai

Interesting, this is a really good point. I don't think there is a way to increase the total contract's `pfc()` without proportionally increasing your sponsor position's share of that `pfc()` and funding rate fees paid. Do you agree?

**Comment by chrismaree** [comment]
> > As stated [here](https://github.com/UMAprotocol/protocol/pull/2168#discussion_r522430148), I don't think this is a vulnerability because I think there's a subtle flaw in the initial analysis (although I could be wrong, so please correct me!!).
> > > 3.d) redeem position created in 3.b. This will return all flashloaned collateral
> > 
> > 
> > I think this is incorrect. The collateral in your position will be proportionally docked, just like everyone else's. Let's do a simple example. Let's say the reward percentage is 10%, and there's $10MM in the contract. You flash loan another $10MM to double the size of the contract (mint some tokens with $10MM worth of collateral). In the non-flash loan case, the $1MM is paid out by the contract. In the flash loan case $2MM is paid out. However, that extra $1MM is coming out of _your position_ (since you are now half of the contract's collateral)! So, on redemption, you would only have 90% of your position left ($9MM) because the cumulativeFeeMultiplier had been changed to 90% of its previous value.
> > Thoughts? Do y'all agree with this analysis?
> > cc @chrismaree @nicholaspai
> 
> Interesting, this is a really good point. I don't think there is a way to increase the total contract's `pfc()` without proportionally increasing your sponsor position's share of that `pfc()` and funding rate fees paid. Do you agree?

yup, I agree with this and that's a great conclusion as it means that while you can increase the PFC & the associated reward you are simply paying yourself the reward from your own account, making this "attack" unimpactful. That's good news :)

We should try and look for any function call combinations that would first calculate the rewards separately to the reward withdrawal step. `_publishRateAndWithdrawRewards` is not vulnerable to this as we compute the reward (based off pfc) in the same function call as the reward transfer. I'm pretty sure there are no other places where this ordering would be posible.
