### ISSUE TITLE
Check for !isContract in optimistic oracle

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#2241]
**Why**

If a requester is not a contract, the callbacks can revert outside of the try-catch, causing the request flow to break.

**How**

We should either:
- Check up-front whether the requester is a contract and revert if not. This solution can still have issues when contracts self destruct.
- Wrap callbacks in if (isContract) to avoid the revert condition entirely.

**Resolution**

Non-contracts no longer cause issues in the optimistic oracle.

**Difficulty Score [1-10]**

- 4: ~2 hours

**Comment by nicholaspai** [comment]
Closed by https://github.com/UMAprotocol/protocol/commit/b54edc735516fa83c64692f40e29bffaa212c453
