### ISSUE TITLE
Readme 404 link to deployed contracts

### ISSUE THREAD

**Issue by Huge** [UMAprotocol/protocol#2348]
"find the addresses of relevant contracts <here>" points to some missing location.

Update: Another missing link is( not) to the Bug bounty.

**Comment by ecs-hk** [comment]
Agreed / adding to this issue:

The top level `README.md` points to `./documentation/developer_reference/bug_bounty.md`. But the `documentation/developer_reference` subdirectory does not exist.

**Comment by smb2796** [comment]
@Huge @ecs-hk thanks for pointing this out. These were fixed in #2570.
