### ISSUE TITLE
Write and test deployment scripts to propose the perp template upgrade

### ISSUE THREAD

**Issue by Tommy1231232** [UMAprotocol/protocol#2441]
Created by Matt Rice via monday.com integration. 🎉

**Comment by mrice32** [comment]
@pemulis Can you verify my logic that we can use:
- https://github.com/UMAprotocol/protocol/blob/master/packages/core/migrations/17_deploy_perpetual_creator.js to do the deployment.
- https://github.com/UMAprotocol/protocol/tree/master/packages/core/scripts/creator-umip to propose adding the creator to the Registry.

If I'm thinking about this correctly, that should be all that's required, meaning no new code needs to be written. Is that correct? If so, we should be able to close this.

**Comment by pemulis** [comment]
I made a few tweaks to the perpetual creator migration code[1], and have yet to test the migration, but, in principle, I don't think any new code needs to be written here.

[1] https://github.com/UMAprotocol/protocol/pull/2445
