### ISSUE TITLE
Refactor our usage of drizzle

### ISSUE THREAD

**Issue by rawfalafel** [UMAprotocol/protocol#332]
Digging into #273 , it's clear that the perf issues are caused by components being unnecessarily rendered. This ticket will address those concerns, possibly by using patterns provided by https://github.com/trufflesuite/drizzle-react. 

Some notes:
* [Drizzle hooks](https://github.com/trufflesuite/drizzle-react#react-hooks-support-experimental) are "experimental", but hooks themselves are fully supported in our version of React. We should probably look into this first.
* [React contexts](https://reactjs.org/docs/context.html) also seem to be important. The general idea is that we can store the drizzle object as a context, and procure it for any child component without passing it down as a parameter every single time.

**Comment by mrice32** [comment]
We're using hooks now!
