### ISSUE TITLE
Mention Correct Node Version in Documentation

### ISSUE THREAD

**Issue by Mentors4EDU** [UMAprotocol/protocol#3606]
This is in response to issue #2288, it gets a Linux compilation/build error for compatibility w/ Yarn if running on Node v10.14. `nvm use 14` fixes this and allows UMA to build w/ Yarn. Please mention node >14 in the docs so people don't run into the same error running a lower version of Nodejs when trying yarn and `yarn qbuild`.

**Comment by daywiss** [comment]
thanks for the suggestion. Its not clear which minimum node 14 version is supported, theres at least one issue we have found internally that wont work below 14.14, but we might fix that. Happy to entertain a PR for this, but I will put it in our backlog.

**Comment by mrice32** [comment]
Nodejs 14 is explicitly mentioned in the docs.

**Comment by Mentors4EDU** [comment]
Hi, this was opened in 2021, the problem been resolved I guess after this ticket was open. Thank you.
