### ISSUE TITLE
Detailed guide with example asset

### ISSUE THREAD

**Issue by EdouardLvdl** [UMAprotocol/protocol#368]
Will you offer a detailed doc/guide for someone to reproduce your S&P 500 smart contract or with another different asset? it could be fun to get initiated with the project and understand how the code works

Thanks!

**Comment by mrice32** [comment]
You can currently get most of the way there with our existing README, but we'll do some cleanup so it's clear how to create an example synthetic asset on ganache.

**Comment by mrice32** [comment]
This is done.
