### ISSUE TITLE
Implement a role-based permissioning contract

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#370]
We should implement a contract that can manage an arbitrary number of roles for permissioning methods each identified by a human-readable name.

**Comment by ptare** [comment]
One way to do build this permissioning contract is to represent roles with strings (or ints), except perhaps for a special admin role. The admin role controls adding and removing addresses from other roles.

A function modifier `onlyForRoles(string role)` could be used by derived contracts to restrict function calls to specific roles. E.g., `function remargin() onlyForRoles("Remarginer")`. Each derived contract defines it own set of roles.

Alternatives that are more type safe but require more boilerplate are definitely possible. Thoughts?

**Comment by mrice32** [comment]
As discussed IRL, I like that proposal^. I prefer a less typesafe but more flexible approach, but I'm definitely open to hear objections on that.
