### ISSUE TITLE
Which issue to tackle first?

### ISSUE THREAD

**Issue by gabriel-horvat** [UMAprotocol/protocol#3955]
Hey guys!

Would love to get involved and help out the project...

The thing is though, there are tons of issues on here most of which are from 2020/2021.

Which makes me think theyre not important to UMA right now, else they'd be worked on.

Long story short, what's a good first relevant issue to work on?

Thanks!

**Comment by nicholaspai** [comment]
Yeah those are outdated, we need to clean them up! What is your software stack knowledge?

**Comment by gabriel-horvat** [comment]
Just wanted to bump this in your inbox ;)

**Comment by mrice32** [comment]
Doing some issue cleanup, but @gabriel-horvat if you're still interested in working on some issues in this repo, a good one to start with would be:
- Removing web3.js and any truffle packages from the dependency tree.
- Updating the entire repo to be compatible with nodejs 20 if it isn't already and updating the docker image to use nodejs 20.
- Looking through the build output `yarn build` and trying to get rid of any warnings you see.

If you'd like to tackle any of these, feel free to open a new issue to track progress!
