### ISSUE TITLE
TypeError: rateModelStore.getV1OptimisticOracleInterfaceAbi is not a function

### ISSUE THREAD

**Issue by lljxx1** [UMAprotocol/protocol#4039]
**Description**

```shell
node_modules/@uma/sdk/dist/src/clients/optimisticOracle/client.ts:16
export const contractInterface = new utils.Interface(getV1OptimisticOracleInterfaceAbi());
                                                     ^
TypeError: rateModelStore.getV1OptimisticOracleInterfaceAbi is not a function
```

**Reproduction**

**Expected Behavior**

**Screenshots**

**Version and OS Info**

 - OS: [e.g. Ubuntu]
 - Version [either git hash of the repository or release]

**Additional Context**

{
 "version": "0.23.4",
  "name": "@uma/sdk",
}

**Comment by mrice32** [comment]
@daywiss does this issue still exist when importing the package?
