### ISSUE TITLE
Run Slither with all detectors enabled

### ISSUE THREAD

**Issue by ptare** [UMAprotocol/protocol#444]
We've disabled many Slither detectors due to false positives, but once we're code complete on the Oracle, we should run Slither with all detectors enabled to make sure nothing slipped through.

**Comment by montyly** [comment]
Hi,

For info, slither has a [triage mode](https://github.com/crytic/slither/wiki/Usage#triage-mode), so you can save the analysis of the false alarms, and Slither won't report them in the future.

**Comment by mrice32** [comment]
@montyly Very cool! We'll definitely try that out!

**Comment by nicholaspai** [comment]
Closing in favor of #988
