### ISSUE TITLE
Upgrading to web3.js v4 w/TypeScript

### ISSUE THREAD

**Issue by mconnelly8** [UMAprotocol/protocol#4634]
Will you be upgrading your web3.js usage to v4 and TypeScript?  I'm with the web3.js team at ChainSafe and we're available to answer any questions about migrating to v4

**Why**

What is the motivation for this feature or task? Migrating to web3.js v4 w/TypeScript

**Resolution**

What is the deliverable to consider this task done?  Upgrading to web3.js v4

**Difficulty Score [1-10]**

This is a measure of the amount of developer time this task will require to be completed. Note: this should include design and planning time in addition to implementation time. The scale is not linear:

- 7: ~3 days

**Comment by mrice32** [comment]
We primarily do not use web3.js anymore. We've mostly moved to ethers. We only have web3.js for legacy code, and we would migrate to ethers if/when that code is updated.
