### ISSUE TITLE
Dispute Assertion function not in OOV3 interface

### ISSUE THREAD

**Issue by pedrovalido** [UMAprotocol/protocol#4668]
**Description**

The dispute assertion is not present in the oov3 interface but is implemented in the oov3. 

**Reproduction**

NA

**Expected Behavior**

NA

**Screenshots**

NA

**Version and OS Info**

 - OS: macOS
 - Browser: Arc
 - Version: ae65deda

**Additional Context**

Can open a PR shortly for this.

**Comment by mrice32** [comment]
Thanks for adding this PR!
