### ISSUE TITLE
Flaky test in Voting.js

### ISSUE THREAD

**Issue by ptare** [UMAprotocol/protocol#559]
The test case `Commit and persist the encrypted price against the same identifier/time pair multiple times` is flaky when `secondEncryptedMessage` is an odd number of hex digits.

In this code:
`const secondEncryptedMessage = web3.utils.toHex(getRandomUnsignedInt());`

If `secondEncryptedMessage` is, for example, "0x1", then the retrieved message becomes "0x01".

One option could be to always pad the `bytes encryptedVote` in `Voting::commitAndPersistEcryptedVote`?

**Comment by mrice32** [comment]
Does this ever cause issues with decryption?

**Comment by ptare** [comment]
As far as I can tell, the encryption/decryption loop works fine. That could be one fix to the flaky test as well. It's still a bit weird that `sendMessage` and `getMessage` don't give you back the same message.

**Comment by mrice32** [comment]
I think this was fixed in #570. @ptare lmk if that's incorrect.
