### ISSUE TITLE
Handle case where batchCommit/batchReveal exceeds gas limit in AVS

### ISSUE THREAD

**Issue by rawfalafel** [UMAprotocol/protocol#562]
Handle the case in `scripts/Voting.js` where `batchCommit` or `batchReveal` exceeds the gas limit.

**Comment by nicholaspai** [comment]
Addressed by #827

**Comment by mrice32** [comment]
@nicholaspai instead of closing manually, I'd suggest adding the following to your PR description:
```
Fixes #562
```

If you do that, then the PR will automatically close the issue when it merges.
