### ISSUE TITLE
Bug: step 3 of tokenbuilder breaks when the user changes account

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#712]
If the user changes their account after loading the dApp, the tokenbuilder doesn't update the address used to send transactions.

**Comment by ptare** [comment]
One way to handle account changes more smoothly is to show a message on screen (maybe a bar at the top or bottom of the page) asking the user to refresh.

**Comment by mrice32** [comment]
If we know that the account is out of date, should we refresh automatically rather than just asking the user to refresh? Or do you think it's more user friendly to show a suggestion?
