### ISSUE TITLE
Consider moving event declarations to be higher up in the file, in conventional spot

### ISSUE THREAD

**Issue by adeelhasan** [UMAprotocol/protocol#744]
https://github.com/UMAprotocol/protocol/blob/08b45b77fb48d885b5ee815a3742213f114caa1c/core/contracts/Voting.sol#L704-L712

[https://solidity.readthedocs.io/en/v0.5.12/style-guide.html](url)

1. Type declarations
2. State variables
3. Events
4. Functions

**Comment by ptare** [comment]
Thanks for the suggestion @adeelhasan! I'm currently making some changes to Voting.sol, and I'll make this change either as part of that upcoming PR or in a follow up.
