### ISSUE TITLE
Suggestion to add support for ERC777 tokens

### ISSUE THREAD

**Issue by adeelhasan** [UMAprotocol/protocol#745]
ERC777 has improvements over ERC20, and is backwards compatible to it.

A good summary is here:
[https://hackernoon.com/erc777-is-the-new-token-standard-replacing-the-erc20-fd6319c3b13](url)

in particular being able to designate an operator for your token sounds useful for a DVM

Given that you are aiming to be a platform, supporting both standards leaves the choice up to the user. For all its advantages though, ERC777 is not so common (at least I havent come across it took much), and as such its complexity is maybe a barrier to adoption, not to mention that ERC20 is too established as a primary token standard That being said, in your case, the choice could be left to the user.

Open Zeppelin has an implementation.

**Comment by mrice32** [comment]
ERC20 is still, for the most part, the minimum expectation we can apply to tokens that this protocol interacts with, so we see it as the minimum expectation we can apply.
