### ISSUE TITLE
Review contract permissions

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#781]
Before launching the DVM, we need to do a review of the permissions in each contract and ensure they match our intended setup. As a part of this, certain permissions should be delegated to the Governor contract.

**Comment by mrice32** [comment]
Proposal:

- TokenizedDerivative and related contracts
  - These will not be deployed with the initial DVM deployment, so their permissions do not need to be reviewed and can remain completely centralized.
- Registry
  - The Governor should control who the Derivative Creators are, meaning the Governor should be the Writer.
  - No one should be able to remove the Governor from that role other than the Governor, so the Governance role should be removed and the Writer role should manage itself.
- Finder
  - To ensure the Governor has final say over upgrades, the governor should directly control the addresses in the Finder, meaning it should hold the Writer role.
  - For the same reason as the Registry, the Governance role should be removed and the Writer role should manage itself.
- Store
  - The Governor contract should assume the Governance role and control all tax and fee rates in the store.
  - To make the store more similar to the other contracts, we should change the name of the Governance role to Writer.
- Voting
  - The Writer role should become an exclusive role.
  - The Governor should assume the Writer role.
  - The Governance role should be removed and the Writer role should be self managed.
- VotingToken
  - The Governor contract should assume the Governance role so it directly controls who is allowed to mint (and burn) for upgrade purposes.

**Comment by mrice32** [comment]
@ptare PTAL at the above proposal.

**Comment by ptare** [comment]
LGTM. Since many contracts will now have only one exclusive role, we should consider whether moving back to OpenZeppelin's Ownable makes sense.

**Comment by mrice32** [comment]
I updated the above with your feedback as well as others on the team.

**Comment by ptare** [comment]
Nice! Just for completeness, in the `Governor` contract itself, the role `Admin` is held by the foundation cold wallet and the role `Proposer` is held by the foundation hot wallet?

**Comment by mrice32** [comment]
Thanks for pointing that out -- yes, that's correct. Added it to the post above.
