### ISSUE TITLE
CI `test` job is not running test files in nested directories

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#794]
When tests in `core/test/scripts/` fail, only the `coverage` job is catching them. I'm not sure why, but it appears that the test job is not running these nested tests. 

As a test, I ran the following command locally:
```
$(npm bin)/truffle test
```
This *did* run the tests in the `scripts/` directory. My suspicion is that it's either something peculiar to the packages installed in the `test` ci job (uses a different installation than `coverage`) or that it's related to the setup or network on the `test` job (uses the `ci` network and has a ganache instance running alongside in a separate image).

**Comment by ptare** [comment]
This issue went away on its own?? @mrice32
