### ISSUE TITLE
Ensure all function calls are invulnerable to caller re-calling draining funds

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#885]
Specifically the function `withdrawLiquidation` in `Liquidatable.sol` could be susceptible to one user calling the function multiple times to drain funds from the position. 

Say a position has been liquidated and successfully disputed. Is it possible for the disputer to call multiple times and drain the position of the funds entitled to others? Right now this check is not 100% explicit or clear and requires better code coverage.

**Comment by nicholaspai** [comment]
Simple way to solve this would be to store extra boolean/uint params in the `LiquidationData` struct that keep track of "if" or "how many" rewards were paid out

`sponsorRewardPaid`, `disputerRewardPaid`, `liquidatedCollateralPostRewardsPaid`

Also, I think this is only a problem if a dispute on a liquidation is **successful**

**Comment by chrismaree** [comment]
I agree. this seems to be the best way of doing it.
