### ISSUE TITLE
Refactor monorepo directory structure into `Lerna` style packages

### ISSUE THREAD

**Issue by nicholaspai** [UMAprotocol/protocol#941]
For example, the following should be their own independent packages (with their own `package.json`'s):
- contracts (currently in `core/`)
- AVS (currently in `core/scripts/Voting.js`)
- Voting CLI (currently in `core/scripts/cli/`)
- Voter dApp (currently in `voter-dapp`)
- Sponsor dApp (currently in `sponsor-dapp-v2`)
- Financial Templates Lib (currently in `financial_templates_lib`)
...

A good example of a [Lerna](https://lerna.js.org/) structure are the [Truffle monorepo](https://github.com/trufflesuite/truffle) and [0x monorepo](https://github.com/0xProject/0x-monorepo)

**Comment by nicholaspai** [comment]
Deprecating in favor of "Lerna Restructure" milestone

**Comment by adrianmcli** [comment]
Linking milestone here for convenience: https://github.com/UMAprotocol/protocol/milestone/13
