### ISSUE TITLE
Documentation page doesn't show anything for "Contracts"

### ISSUE THREAD

**Issue by rcai1** [UMAprotocol/protocol#952]
On the documentation page (https://docs.umaproject.org/uma/index.html), there are links to see tutorials and explainers, but there doesn't seem to be a way to access information about different contracts. For example - I couldn't figure out how to get to this page: https://docs.umaproject.org/uma/contracts/ExpiringMultiParty.html

**Comment by mrice32** [comment]
Are you sure you don't have the contracts tab minimized on the left panel? It's also a separate scroll bar, so you may need to scroll down on the left panel to see them. Here's a screenshot of what I see:
![Screen Shot 2020-02-21 at 11 00 21 AM](https://user-images.githubusercontent.com/11791551/75050202-8b2e0580-5499-11ea-8005-8d0e22fcfdd3.png)

**Comment by nicholaspai** [comment]
when browser window is too small, "Contracts" tab can be hidden upon initial load
