### ISSUE TITLE
CLI utility shows wrong etherscan links when generating tx

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#953]
Right now the CLI utility always generates a link to etherscan.io, even if running on test net or local.
![image](https://user-images.githubusercontent.com/12886084/75053282-fb8b5580-549e-11ea-82fc-7622b9170859.png)
This should dynamically change based on the network.

**Comment by mrice32** [comment]
Agreed, we have a common lib that should help with that: https://github.com/UMAprotocol/protocol/blob/master/common/PublicNetworks.js.

We use it in the sponsor dapp to generate etherscan links: https://github.com/UMAprotocol/protocol/blob/b6844d3baef83df5f01c5032b8621970441c09f1/sponsor-dapp-v2/src/lib/custom-hooks.js#L53-L66

**Comment by nicholaspai** [comment]
Added a fix for this in #951
