### ISSUE TITLE
Remove prettier ignore on `override` methods and inline assembly calls (breaking changes in Solidity 0.6)

### ISSUE THREAD

**Issue by nicholaspai** [UMAprotocol/protocol#969]
Prettier Solidity plugin cannot differentiate `override` methods, outstanding issue [here](https://github.com/prettier-solidity/prettier-plugin-solidity/issues/221) which is blocked by a solidity parsing library [here](https://github.com/ConsenSys/solidity-parser-antlr/issues/2)

I looked into forking the two repos and fixing ourselves. I believe the `prettier-plugin-solidity` changes are easier to implement (see [here](https://github.com/prettier-solidity/prettier-plugin-solidity/pull/228/files) for an example of how they recently added ability to detect `virtual` methods). However, the `solidity-parser-antlr` changes involve quite a bit of hardcoded variables. For example, look at how they [handled virtual functions](https://github.com/ConsenSys/solidity-parser-antlr/commit/0d9bf261ef3d0df1e035869760beb7a8bf0d0c2f#diff-fe8df1ee9aee757690a53907b2b05703)

___

~~Separately, `prettier-plugin-solidity` does not handle the new syntax for inline assembly opcodes, see [the issue](https://github.com/prettier-solidity/prettier-plugin-solidity/issues/238)~~ Fixed by alpha.42

**Comment by fvictorio** [comment]
Hey @nicholaspai, just wanted to say thanks for giving `prettier-solidity` a try. These two issues are very high priority for us, I hope we have them ready soon!

**Comment by nicholaspai** [comment]
Assembly opcodes bug [fixed](https://github.com/prettier-solidity/prettier-plugin-solidity/issues/238)! @fvictorio

**Comment by fvictorio** [comment]
Yep :smile: I think only the `override` part is left, which should be fixed in the parser soon. After that I think it will be easy to add to prettier-solidity.
