### ISSUE TITLE
Refactor `liquidatable.sol` modifiers to use seperate function definitions for state checks

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/protocol#984]
Right now `liquidatable.sol`'s modifiers perform state checks within the modifiers. This should be consistent with how `PricelessPositionaManager.sol` leverages separate functions to inform state checks.

**Comment by nicholaspai** [comment]
@chrismaree I didn't make these changes because they didn't reduce bytecode size (they are each only used once as a modifier) but I support this for the sake of consistency

**Comment by chrismaree** [comment]
> @chrismaree I didn't make these changes because they didn't reduce bytecode size (they are each only used once as a modifier) but I support this for the sake of consistency

Ok cool but the main thing for me is consistency.
